/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119201-g4d4b301e4a-20250410"
#endif /* AVUTIL_FFVERSION_H */
